### PR TITLE
added getters for operations and unit-tests

### PR DESCRIPTION
**Pull request by roman-1983**
Hi Jan,

i have added getters for several operations and unit-tests, too.

### CODE REVIEW

**Comment by Exeu** [comment]
@roman-1983 you need to check if the array key exists before returning its value. otherwise this ends up with a php notice. 

would be nice if you add isset($this->params[$key]).
Note that this needs also to be tested.

**Comment by Exeu** [comment]
Build fails

**Comment by roman-1983** [comment]
Hi Jan,
did you see the error? PHP 5.3.3 failed with following error

>   [RuntimeException]                                                           
> The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl extension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true. 

This has nothing to do with the getters

**Comment by Exeu** [comment]
Hey Roman,

the "Build fails" message was not posted by me. This was my new Continuous Integration environment which now is able to write comments and was tested yesterday evening.

No worries ;) I know that the 5.3.3 env in travis is broken but the message was not coming from travis at all.

Cheers

**Comment by roman-1983** [comment]
haha ok :)

**Pull request merged**
