### PR TITLE
Add sort option to Search Operation

### PR DESCRIPTION
**Pull request by Molkobain**
Added a setSort method

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/SortingbyPopularityPriceorCondition.html

### CODE REVIEW

**Comment by LeFrenchie** [comment]
Hello, some news about this request ?

**Comment by alexpli** [comment]
+1

**Comment by jdlferreira** [comment]
+1!

**Comment by Exeu** [comment]
This will not be merged until there is a test case.

**Pull request closed without merging**
